# Generated by Django 4.2.5 on 2023-09-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account', models.UUIDField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(max_length=100)),
                ('account_url', models.URLField(unique=True)),
                ('name', models.CharField(blank=True, max_length=200, unique=True)),
                ('followers', models.BigIntegerField(blank=True)),
                ('profile_image_url', models.TextField(blank=True, max_length=5000)),
                ('bio', models.TextField(blank=True, max_length=5000)),
            ],
            options={
                'db_table': 'social_account_info',
            },
        ),
    ]
